server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: jwo-auth-service-poc
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    com.jwo: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Metrics configuration
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      simple:
        enabled: true
  endpoint:
    health:
      show-details: always
